version: '3.8'

services:
  pg_master:
    image: bitnami/postgresql:latest
    container_name: pg_master
    user: root
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=minh_admin
      - POSTGRESQL_PASSWORD=minh_password
      - POSTGRESQL_DATABASE=distributed_db
    volumes:
      - pg_master_data:/bitnami/postgresql

  pg_slave:
    image: bitnami/postgresql:latest
    container_name: pg_slave
    user: root
    ports:
      - "5433:5432"
    depends_on:
      - pg_master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=pg_master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_PASSWORD=minh_password
    volumes:
      - pg_slave_data:/bitnami/postgresql

volumes:
  pg_master_data:
  pg_slave_data: